baseURL: "https://johnforstmeier.com/"
languageCode: "en-us"
title: "John Forstmeier"
theme: "forstmeier"
publishDir: "."
staticDir: "static"

params:
  about:
    - I'm a senior engineer and the first hire at Shipyard. On nights and weekends I'm building Pocket Size Fund as a side project. I've made several angel investments and plan on making more. In my spare time I enjoy reading and lifting.
    - I'm pro-West, pro-growth, and pro-human.
    - This website's content edits can be found in its public GitHub repository.
  links:
    - name: Twitter
      url: https://twitter.com/forstmeier
    - name: GitHub
      url: https://github.com/forstmeier
    - name: Instagram
      url: https://www.instagram.com/johnforstmeier/
    - name: LinkedIn
      url: https://www.linkedin.com/in/johnforstmeier/
    - name: AngelList
      url: https://angel.co/u/forstmeier
    - name: Automated Capital
      url: https://automated.capital/