baseURL: "https://johnforstmeier.com/"
languageCode: "en-us"
title: "John Forstmeier"
theme: "forstmeier"
publishDir: "."
staticDir: "static"

params:
  about:
    - John is a senior full stack engineer at Shipyard. His personal activities include working on side projects, writing, reading, and lifting.
    - John is interested in early-stage startups working on platforms in the nuclear energy, advanced manufacturing, and space sectors. He is pro-West, pro-growth, and pro-human.
    - John can be reached via direct message on Twitter and enjoys collaborating with similarly-interested individuals.
  links:
    - name: Twitter
      url: https://twitter.com/forstmeier
    - name: GitHub
      url: https://github.com/forstmeier
    - name: Instagram
      url: https://www.instagram.com/johnforstmeier/
    - name: LinkedIn
      url: https://www.linkedin.com/in/johnforstmeier/
    - name: AngelList
      url: https://angel.co/u/forstmeier
    - name: Automated Capital
      url: https://automated.capital/