baseURL: "https://johnforstmeier.com/"
languageCode: "en-us"
title: "John Forstmeier"
theme: "forstmeier"
publishDir: "."
staticDir: "static"

params:
  about:
    - John is a senior engineer at Shipyard and founder at Automated Capital. In his spare time he enjoys building side projects, writing, reading, and lifting.
    - John's goals are to work in a hard-tech industrial sector and to join a startup founding team.
    - John can be reached via direct message on Twitter.
  links:
    - name: Twitter
      url: https://twitter.com/forstmeier
    - name: GitHub
      url: https://github.com/forstmeier
    - name: Instagram
      url: https://www.instagram.com/johnforstmeier/
    - name: LinkedIn
      url: https://www.linkedin.com/in/johnforstmeier/
    - name: AngelList
      url: https://angel.co/u/forstmeier
    - name: Automated Capital
      url: https://automated.capital/